spring:
  application:
    name: server
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://34.86.77.107:5432/Proyecto-TIC-I
    username: postgres
    password: pedorro123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    ROOT: INFO



